ヘッダーを実装しました。その際に各ページのルーティングも行いました。
Ryo-Sasaki-xxx/morizoe-portfolio pull request #6
Opened 2023-10-18 21:56 UTC by Ryo-Sasaki-xxx

このブランチでやったこと
1.ヘッダーのレイアウトとその中のh1 buttonなどを実装した。
2. 各ページのルーティングを実装した。

2023-10-18 23:04 UTC, syu-sasaki commented on morizoe-portfolio/src/components/global/header/Header.jsx
Headerフォルダいらなくね？

2023-10-18 23:29 UTC, Ryo-Sasaki-xxx commented on morizoe-portfolio/src/components/global/header/Header.jsx
消します

2023-10-18 23:38 UTC, syu-sasaki requested changes

2023-10-18 23:38 UTC, syu-sasaki commented on morizoe-portfolio/src/components/global/header/Header.jsx
> +        <SHeader $backgroundColor={"red"}>
カラー指定の消し忘れ？

2023-10-18 23:38 UTC, syu-sasaki commented on morizoe-portfolio/src/components/global/header/Header.jsx
> +    // ${props => props.$isActiveMenue && "width: 2.5rem;"}
コメントアウトの消し忘れ

2023-10-18 23:38 UTC, syu-sasaki commented on morizoe-portfolio/src/components/global/header/Header.jsx
> +    // ${props => props.$isActiveMenue && "width: 2.5rem;"}
コメントアウト消し忘れ

2023-10-19 01:20 UTC, Ryo-Sasaki-xxx commented on morizoe-portfolio/src/components/global/header/Header.jsx
> +        <SHeader $backgroundColor={"red"}>
そです

2023-10-19 01:20 UTC, Ryo-Sasaki-xxx commented on morizoe-portfolio/src/components/global/header/Header.jsx
> +    // ${props => props.$isActiveMenue && "width: 2.5rem;"}
こっちもそです

2023-10-19 13:31 UTC, syu-sasaki approved these changes
おそらく大丈夫

2023-10-19 13:31 UTC, merged